# Generated by Django 2.1 on 2018-08-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('delete', 'DELETE'), ('patch', 'PATCH'), ('put', 'PUT')], max_length=8)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField(blank=True)),
                ('status', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
