# Generated by Django 2.1 on 2018-08-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='body',
        ),
        migrations.AddField(
            model_name='services',
            name='params',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.IntegerField(),
        ),
    ]
