# Generated by Django 2.1 on 2018-08-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_auto_20180813_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
